spring.datasource.driver-class =org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://3.21.205.138:5432/falabella
spring.datasource.username=postgres
spring.datasource.password=cristianroa.123

gseguel.swagger.enabled=true
spring.mvc.pathmatch.matching-strategy=ant-path-matcher